### ISSUE TITLE
Shutter does not Install properly on Ubuntu 18.10

### ISSUE THREAD

**Issue by bettinson** [grepsedawk/.dotfiles#19]
* Missing dependency shutter:

```
E: Package 'shutter' has no installation candidate
```

* Packages installed but no longer required:
```
The following packages were automatically installed and are no longer required:
  fonts-liberation2 fonts-opensymbol gir1.2-geocodeglib-1.0 gir1.2-gst-plugins-base-1.0 gir1.2-gstreamer-1.0 gir1.2-gudev-1.0
  gir1.2-udisks-2.0 grilo-plugins-0.3-base guile-2.2-libs libboost-date-time1.67.0 libboost-filesystem1.67.0 libboost-iostreams1.67.0
  libboost-locale1.67.0 libcdr-0.1-1 libclucene-contribs1v5 libclucene-core1v5 libcmis-0.5-5v5 libcolamd2 libdazzle-1.0-0 libe-book-0.1-1
  libeot0 libepubgen-0.1-1 libetonyek-0.1-1 libexiv2-14 libfreerdp-client2-2 libfreerdp2-2 libgc1c2 libgee-0.8-2 libgexiv2-2 libgom-1.0-0
  libgpgmepp6 libgpod-common libgpod4 liblangtag-common liblangtag1 liblirc-client0 libmediaart-2.0-0 libminiupnpc17 libmspub-0.1-1
  libodfgen-0.1-1 libqqwing2v5 libraw16 librevenge-0.0-0 libsgutils2-2 libssh-4 libsuitesparseconfig5 libvncclient1 libwinpr2-2 libxapian30
  libxmlsec1 libxmlsec1-nss lp-solve media-player-info python3-mako python3-markupsafe syslinux syslinux-common syslinux-legacy
  usb-creator-common
```

**Comment by grepsedawk** [comment]
@bettinson Thanks for the report!
Was shutter the only dependency that seemed to be missing during your installation?

It does look like this ppa was added to take care of shutter: https://launchpad.net/~shutter/+archive/ubuntu/ppa

I'll try to add 18.10 to circle later and make it work. In the meantime, if you are missing out on shutter, I believe this should work to install shutter:

```shell
sudo add-apt-repository ppa:shutter/ppa
sudo apt update
sudo apt install shutter
```

Happy hacking

**Comment by grepsedawk** [comment]
Flagging as both a bug an enchancement because it breaks 18.10 installation, but 18.10 wasn't technically supported.

I should also probably add a "supported versions" section to the readme

**Comment by grepsedawk** [comment]
I've removed it for now to get a rebuild in tonight (https://github.com/grepsedawk/.dotfiles/commit/8e37aaf2add9dcde23652ba09a81aadd27b9fc61), but I'm leaving this issue open because I'd like to re-implement shutter in the install scripts.

**Comment by bettinson** [comment]
bump

**Comment by grepsedawk** [comment]
New way of taking screenshots is to run this script on a keybind: https://github.com/grepsedawk/.dotfiles/blob/master/.i3/screenshot
